micronaut:
  application:
    name: micronaut-grpc-client
  server:
    port: 9080

grpc:
  channels:
    demo-service:
      address: localhost:8080
      negotiationType: plaintext
      max-retry-attempts: 10
